model = model.Sequential()
model.add(layers.Dense(16, activation='relu', input_shape=(10000,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(16, activation='relu')
model.add(layers.Dropout(0.5))
model.add(layers.Dense(1, activation='sigmoid'))